### ISSUE TITLE
Error when I upload to Web Server

### ISSUE THREAD

**Issue by premudeshi** [fethica/PHP-Login#101]
When I try to run this system on a Debian server, it gives me an HTTP 500 internal error. What does this mean and what can I do to fix this?

Thanks,
Prem

**Comment by DSMTurboAWD** [comment]
Do you have Apache2 or ampps running on the server?

**Comment by premudeshi** [comment]
Apache2, with mysql

**Comment by DSMTurboAWD** [comment]
Can you verify it is running (Apache2)
are you using ampps or lamp etc.?

**Comment by premudeshi** [comment]
I have fixed the error, it was an SQL error, its all working!
