### ISSUE TITLE
500 Server Error

### ISSUE THREAD

**Issue by renzosalvador** [fethica/PHP-Login#103]
Hi, I am getting a 500 Server Error regarding the createuser.php in the browser console.
The DB connection is OK, as it adds the user to the table.
![screen shot 2017-08-08 at 11 40 55](https://user-images.githubusercontent.com/3306934/29068440-c597fa82-7c2e-11e7-8a36-3955cb355450.png)
Any advise?

**Comment by DSMTurboAWD** [comment]
Error 500 typically means the Apache server is not running or the server is down
Could you verify that your Apache server is running?

**Comment by renzosalvador** [comment]
Thank you I got it. I didn't copy over the PHPMailer Script.
