### ISSUE TITLE
Error Internal with jquery

### ISSUE THREAD

**Issue by LudinJozabeth** [fethica/PHP-Login#12]
Hi fathica! My name is Ludin I'm from Venezuela.
I am using your code login-php, in my pc (mac), it's works! but in my server (centos) don't work..
I don't know why?? Can you help me?? please!!

....

Thank you for answering so quickly!
I managed to find my mistake, was the configuration of apache php-pdo needed to run this code.
Thank you, excellent contribution!

**Comment by fethica** [comment]
@LudinJozabeth Glad you have it resolved 👍
