### ISSUE TITLE
Password reset

### ISSUE THREAD

**Issue by factulas** [fethica/PHP-Login#121]
Any chance we can get a password reset page? Mariadb console is cumbersome for any people not familiar with it.

**Comment by therecluse26** [comment]
Hi, this already exists in the dev branch. Clone it using this command:

git clone -b dev https://github.com/fethica/PHP-Login.git

Then navigate to whatever your sites's base directory is +
/install/index.php to run the automated installation process. If this
fails for whatever reason, try again using the manual installation
method. If that fails, you may have to do some extra legwork to get it
running. It's still a dev version, so ymmv, but it is fairly reliable
on most systems, from what I've seen. Just make sure that your server
satisfies all of the requirements, including having a working PHP CLI

**Comment by factulas** [comment]
Well, hell, where do I see what branches there are.. They used to be at the top by the issues/ etc.
