### ISSUE TITLE
PHPMailer 6.0 PHPMailerAutoload.php doesn't exist

### ISSUE THREAD

**Issue by BrokenAngeLa** [fethica/PHP-Login#126]

**Comment by tomcatbuzz** [comment]
If you look in the code tree, the PHP Mailer module is located in the scripts folder

**Comment by SammF10930** [comment]
As mentioned previously, this can be found by browsing the code tree. Alternatively, if you just want to download a single file, you can click on the "releases" tab and download the full release which has these included.

**Comment by BrokenAngeLa** [comment]
It's working now, Thank you.
