### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by rackbox** [fethica/PHP-Login#13]
Fatal error: Call to undefined function password_verify() in /usr/local/pem/vhosts/100582/webspace/httpdocs/legiskolen.dk/ab/login/scripts/class.loginscript.php on line 65

It seems that class.loginscript.php is the only file containing verify_password(), so I can't figure out where the function is defined

**Comment by therecluse26** [comment]
Hi @rackbox, password_verify is a standard function built into PHP 5.5+ 

Try upgrading your PHP version, that should fix your issue :)
