### ISSUE TITLE
Get the username

### ISSUE THREAD

**Issue by Gerrymandered** [fethica/PHP-Login#139]
Is there any way of getting the username of the person signed in?

**Comment by shaunrc493** [comment]
Do you mean where the user can see the logged in account, or an admin can see who is logged in?

**Comment by shaunrc493** [comment]
Inside login/createuser.php try this:

`if ($response == 'true') {

            echo '<div class="alert alert-success"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>'. $signupthanks .'</div><div id="returnVal" style="display:none;">true</div>';

            $to1 = "example@adminemail.com";
            $to2 = $newemail;
            $subject = "Welcome, $newuser";
            
            $txt1 = "
A new user has just created an account!
            
Their details are:
----------------------
USERNAME: $newuser
PASSWORD: $pw1
E-ADDRESS: $newemail
-----------------------
                      
Admin";

            $txt2 = "
$newuser,

Your account has been created. Verify some stuff....

Admin";
           
            mail($to1, $subject, $txt1);
            mail($to2, $subject, $txt2);
            
        } else {
            //Failure
            mySqlErrors($response);`

**Comment by shaunrc493** [comment]
well that snippet failed xD

hopefully you can read / use that though

**Comment by Gerrymandered** [comment]
user can see the logged in account.

I'm planning to have it so it says something along the lines of:
"<p>Welcome [user].</p>"

**Comment by wbitholedotbe** [comment]
$_SESSION['username']

**Comment by Gerrymandered** [comment]
Thanks, I believe that worked!
