### ISSUE TITLE
Signup form doesnt work

### ISSUE THREAD

**Issue by marcosacramento** [fethica/PHP-Login#14]
I just installed according to instructions but the sign up form gives me 500 (Internal Server Error) in createuser.php

**Comment by therecluse26** [comment]
@marcosacramento Could you give me the output of your PHP error log, please?

**Comment by marcosacramento** [comment]
This is what comes up in the console after clicking the button:
jquery.js:9631 POST http://www.p+++.pt/login/createuser.php 500 (Internal Server Error)
send @ jquery.js:9631
ajax @ jquery.js:9176
(anonymous function) @ signup.js:14
dispatch @ jquery.js:4641
elemData.handle @ jquery.js:4309

**Comment by therecluse26** [comment]
@marcosacramento that's your web client's error output, I need the server side PHP error log. If you're on windows, it's typically in C:\Windows\temp\php_errors.log . I just need the most recent few errors (check the timestamp).

Thanks

**Comment by marcosacramento** [comment]
yes, you were right, from the log, i figured out that i was missing class.phpmailer.php.
Already solved.
Thanks!

**Comment by therecluse26** [comment]
No problem, glad you got it resolved!
