### ISSUE TITLE
Hash Salt?

### ISSUE THREAD

**Issue by tmblog** [fethica/PHP-Login#22]
Hello thanks for the great script, just wondering if the password gets salted before it gets inserted into the db, couldn't see a field in the database.

Thanks

**Comment by therecluse26** [comment]
On Wed, Jul 13, 2016 at 10:07 AM, tmblog <notifications@github.com> wrote:

> Hello thanks for the great script, just wondering if the password gets
> salted before it gets inserted into the db, couldn't see a field in the
> database.
>
>
Yep! It gets hashed and salted in the code.


-- 
- bradley david

**Comment by therecluse26** [comment]
The password_hash function salts the password by default. From PHP.net: "If
omitted, a random salt will be generated by password_hash() for each
password hashed. This is the intended mode of operation."

On Wed, Jul 13, 2016 at 10:07 AM, tmblog <notifications@github.com> wrote:

> Hello thanks for the great script, just wondering if the password gets
> salted before it gets inserted into the db, couldn't see a field in the
> database.
>
> Thanks
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/fethica/PHP-Login/issues/22>, or mute the thread
> <https://github.com/notifications/unsubscribe/AH24AleTCjEfRr3jLoVnEur5oycqe1-lks5qVPE7gaJpZM4JLdKF>
> .
>



-- 
- bradley david

**Comment by tmblog** [comment]
Thank you.
