### ISSUE TITLE
Innodb

### ISSUE THREAD

**Issue by tmblog** [fethica/PHP-Login#24]
Hello, I'm plugging this into one of my programs, the rest of the tables are myIsam, would I have any issues going forward changing the login tables to myIsam? I don't require any locking or referential integrity checking as such.
Thanks

**Comment by therecluse26** [comment]
I just tested it on myIsam and it worked perfectly for me. I would suggest
spinning up a test database just to make sure you don't break something in
your application :)

On Thu, Jul 14, 2016 at 8:49 AM, tmblog <notifications@github.com> wrote:

> Hello, I'm plugging this into one of my programs, the rest of the tables
> are myIsam, would I have any issues going forward changing the login tables
> to myIsam? I don't require any locking or referential integrity checking as
> such.
> Thanks
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/fethica/PHP-Login/issues/24>, or mute the thread
> <https://github.com/notifications/unsubscribe/AH24AuTVwPL2tnrH1_TFqTwrfHNHH-0yks5qVjBCgaJpZM4JMZin>
> .
>



-- 
- bradley david

**Comment by tmblog** [comment]
Thank you. I thought you might have written something programmatically to enforce locking etc. So good to know. Thanks again.
