### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by Lynnstrum** [fethica/PHP-Login#27]
I downloaded it, placed it in my XAMP folder
But when I fill out Signup.php it gives me

Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [1045] Access denied for user 'user'@'localhost' (using password: YES)' in C:\xampp\htdocs\clogin\login\includes\dbconn.php:18 Stack trace: #0 C:\xampp\htdocs\clogin\login\includes\dbconn.php(18): PDO->__construct('mysql:host=loca...', 'user', 'password') #1 C:\xampp\htdocs\clogin\login\createuser.php(41): DbConn->__construct() #2 {main} thrown in C:\xampp\htdocs\clogin\login\includes\dbconn.php on line 18

I also created the tables in phpmyadmin, the stuff posted I pasted into PHP Terminal to auto create everything. After creating 'login'

**Comment by Firestorm-Graphics** [comment]
generally you get that error if something like your password, database name or host has been entered wrong in the dbconfig.php file. did you enter your credentials into that file ?

**Comment by Lynnstrum** [comment]
I got it to work, I was indeed entering something wrong.
Thank you.
