### ISSUE TITLE
How can I set my own cookie after authentication?

### ISSUE THREAD

**Issue by securisec** [fethica/PHP-Login#36]
Hello, how can i add my own cookie after a successful authentication? I want to add a cookie that is randomly generated and all it. mycookie.

Thanks!

**Comment by therecluse26** [comment]
Hi, sorry for the delay in responding. Were you able to fix the problem? I'll be adding this feature in a future release, but for now, this should be a good place to start

http://php.net/manual/en/function.setcookie.php
http://www.w3schools.com/php/func_http_setcookie.asp

**Comment by securisec** [comment]
Thanks Brad. Yes, I did end up fixing it.

**Comment by m1guelpiedrafita** [comment]
If you fixed it, maybe you could do a pull request...
