### ISSUE TITLE
Add exit to loginheader.php

### ISSUE THREAD

**Issue by stee1rat** [fethica/PHP-Login#46]
Hello,

I think it would be a good idea to add `exit;` to loginheader.php, so the content of the page from which it is called wouldn't get executed in case the user is not logged in.

```
<?php
//PUT THIS HEADER ON TOP OF EACH UNIQUE PAGE
session_start();
if (!isset($_SESSION['username'])) {
    header("location:login/main_login.php");
    exit;
}

```

**Comment by therecluse26** [comment]
Good idea! Just added it into my updates. Thanks!
