### ISSUE TITLE
Syntax error in class.loginscript.php

### ISSUE THREAD

**Issue by eagleDiego** [fethica/PHP-Login#5]
Hi, testing the script I realized that [/login/scripts/class.loginscript.php](https://github.com/fethica/PHP-Login/blob/master/login/scripts/class.loginscript.php) at row 58 contains a syntax error.
It should read:
```php
$stmt->bindParam(':myusername', $myusrname);
```
Hope this helps!

**Comment by fethica** [comment]
Hi @eagleDiego , it has been fixed thanks :+1:

**Comment by therecluse26** [comment]
@eagleDiego Good catch, thanks!
