### ISSUE TITLE
Database credentials exposed

### ISSUE THREAD

**Issue by JanPetterMG** [fethica/PHP-Login#51]
Just got this error, of course I need to fix the MySQL permissions, but exposing the password in case of an error is just very dangerous. #security

> Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[28000] [1045] Access denied for user 'login_script'@'example.com' (using password: YES)' in /(..)/login/includes/dbconn.php:18 Stack trace: #0 /(..)/login/includes/dbconn.php(18): PDO->__construct('mysql:host=*****', 'login_script', '**********') #1 /(..)/login/createuser.php(36): DbConn->__construct() #2 {main} thrown in /(..)/login/includes/dbconn.php on line 18

DDOS the SQL server, try to login with random user/pass, congratulations you'll now know the credentials to the database!!!

I'm using the latest `master`.

**Comment by therecluse26** [comment]
VERY good catch, thank you!
