### ISSUE TITLE
PHPMailer Vulnerability 

### ISSUE THREAD

**Issue by jb-alvarado** [fethica/PHP-Login#53]
Hello! First I want to say thank you for your nice project!

Maybe you have hear about it - somebody found a critical vulnerability in PHPMailer:
[phpmailer](http://thehackernews.com/2016/12/phpmailer-security.html)

It is fixed already, but I think PHP-Login use a older Version. 

Is it a problem to update the PHPMailer?

**Comment by fethica** [comment]
Hi @jb-alvarado 

Thanks! I updated the PHPMailer submodule of the project, it works fine no problem. 

You can update the submodule manually to the latest version:

`$ cd login/scripts/PHPMailer/`
`$ git pull origin master`

**Comment by jb-alvarado** [comment]
Hi fethica, thank you for the fast fix! I update phpmailer in that way and yes everything still works.

**Comment by therecluse26** [comment]
Note: in the upcoming version (I swear it's coming, lol), dependencies will
be handled through Composer so we won't have to do the silly submodule game
or use git recursion.

**Comment by fethica** [comment]
Cool! Looking forward to it 👍
