### ISSUE TITLE
I am not Reciveing  Verification email

### ISSUE THREAD

**Issue by syedmustafa54** [fethica/PHP-Login#55]
**Thank you for signing up! You will receive an email shortly confirming the verification of your account.**
But i am not getting any email i have   added phpMailer downloade from https://github.com/PHPMailer/PHPMailer/tree/9e4b8fb3deb7d9cfa515c04cec41f71bc37ce9a9 
But still having error please help me out this is my first question on github

**Comment by therecluse26** [comment]
Hi, have you properly added your smtp credentials? Those should be added in
config.php

**Comment by syedmustafa54** [comment]
Yes i have changed it properly added gmail account but i am trying to send with wamp may be thats the problem do you know any thing that would send email through local host i have added php_smpt dill but still problem may be it will work fine in server.Thanks for the Reply Brad.

**Comment by therecluse26** [comment]
I'm working with MAMP and I'm able to send from PHPMailer by authenticating
my gmail account. It did break for me a while back though when I turned on
two-factor authentication. You may have either disable two-factor auth to
get it working or alternatively generate an app-specific password.

Try this:
https://support.google.com/accounts/answer/185833?hl=en

**Comment by JanPetterMG** [comment]
I'm using gmail too, with two-factor enabled, working like a charm!
The app-specific password is generated at this specific page:
https://security.google.com/settings/u/1/security/apppasswords

**Comment by syedmustafa54** [comment]
can you send me demo project because its not working for me may be php mailer problem so can you please give me your demo project

**Comment by JanPetterMG** [comment]
@syedmustafa54 I'm using `master`, downloaded using composer.
Make sure your `config.php` is using the correct SMTP server configuration, and that the username is your full gmail address.
```php
$from_email = 'example@gmail.com';
$mailServerType = 'smtp';
$smtp_server = 'smtp.gmail.com';
$smtp_user = 'example@gmail.com';
$smtp_pw = '****************';
$smtp_port = 465;
$smtp_security = 'ssl';
```

**Comment by syedmustafa54** [comment]
ya its working  but how to hide email id and password from script
