### ISSUE TITLE
Some good suggestions.

### ISSUE THREAD

**Issue by eddiethejibson** [fethica/PHP-Login#66]
Hello,

Big fan of your project, thanks so much for creating it! 

Just some suggestions that wouldn't be hard to implement, but would enhance this so much (In order of importance):

- A "Forgot Password" Function. Sends an email with the ability to the user to follow the link and reset their password. 

- A "Remember Me" check box which is pretty evident what it does.

- Encrypted Passwords (Perhaps use bcrypt, sha256 or md5?)

While I'm not great with Backend, I would be happy to help you with frontend if it's ever needed (Especially a Material design which would make this look even more beautiful).

Thank-you!

Eddie

**Comment by therecluse26** [comment]
Hey Eddie, I'd definitely be open to some help with the visual side of things. I actually have already added all of those features (password hashing is more secure than encryption, which is what was already implemented in the version that you're using) in the current version I'm working on (plus lots and lots more). 

One idea I was actually thinking of implementing was a sort of theme generator that would allow the user to use color pickers to create their color scheme and alter the CSS automatically... what do you think about that as an idea?

**Comment by VA7NFH** [comment]
Hi @eddiethejibson,
Just so you know "Forgot Password" and "Remember Me" both exist in the [dev branch](https://github.com/fethica/PHP-Login/tree/dev).

**Comment by eddiethejibson** [comment]
@VA7NFH @therecluse26 Sorry about that, I haven't actually checked the recent version recently, I was using an older version - I didn't realise how much had been added! Next time, I'll make sure to check over before submitting suggestions.

Regarding your Color scheme idea, I think that would be a very good enhancement. However, I think it would look even better with a Material theme? If you'd like, I could fork this and customise the front-end with the Materialize framework. If you like it maybe you could include it in your main repository? 

On discovery of how much had been changed, I tested out trying to install it on my test server (http://eddiej.pw) but user accounts aren't being created? I have created the database along with installing PHPMailer - any ideas?

Thanks again and apologies once again for my initial mistake.

Eddie

**Comment by therecluse26** [comment]
@eddiethejibson, no problem! And I'd love to see it it with a different framework than bootstrap. I could even allow the user to switch between them during the installation process, which would give them more development options. I think it's an awesome idea! 

As for the dev branch, I'm still tweaking some things up on it (such as tightening down the mail functionality), so the one you pulled may be slightly out of date with what I have, but not in any huge way. You should be able to navigate to the install folder in the root of the application (so like, localhost/PHP-Login/install/index.php ) and run through the installer that way. That'd be the easiest way to go about it, currently. I'm writing up documentation currently on how to go through the manual process, but it's slow going, as I have 10 different irons in the fire right now, as I'm sure you can relate :P 

Getting there, I promise! I'm definitely looking forward to hearing some more suggestions

**Comment by therecluse26** [comment]
@eddiethejibson, I'm also planning on moving what's in the dev branch currently over to my page and taking more ownership over the project, since I've been the primary developer on this, so I can establish some sort of branding to it. If you want to help me out with that aspect, I'd be very appreciative. I'm trying to think of a fitting project name, and my creativity is running dry. Once I figured something out, I was planning on designing a logo and eventually a website for the project, so if you wanted to help in that regard, I could definitely use it.

**Comment by VA7NFH** [comment]
@therecluse26, very good idea I will try and think of something and get back to you.

**Comment by therecluse26** [comment]
Thanks @VA7NFH !

**Comment by eddiethejibson** [comment]
@therecluse26 Definitely! When it comes to names, I'm pretty awful. However, Front-End development and would be more than happy to help you out with that. I'll fork this tomorrow and start on the Material design. Expanding on the color customisation idea, perhaps the user only can choose a list of colors which suit the page the best? Maybe from http://flatuicolors.com? Some gradients (http://uigradients.com) would make the page look very clean depending on it's use. I actually have a good idea for a sort of clean Dashboard feature which I'll try and add on my "forked" version too. I've got a few servers handy, and would be more than happy to host the project website on them? It would save you both time and money.

Let me know your thoughts.

Thanks Again,

Eddie

**Comment by therecluse26** [comment]
@eddiethejibson , to clarify, when I'm saying "user" in this context, I'm really meaning the admin. I don't know fi you've noticed, but there is a "site settings" option in the drop down menu of a superadmin, which allows them to edit most of their website's configuration settings. I could include a link to the style generator in the same way and restrict access to only the superadmin.

But yeah, we could definitely have it generate recommended color schemes as well, that would be awesome. 

And thanks for offering the server! I was thinking of just doing it as a github page and using it to link to releases and host documentation, mostly, so that would save us both the need to worry about hosting it ourselves. I believe you can generate them with jekyll, so we'd just need to write up the content and sass code.

**Comment by eddiethejibson** [comment]
@therecluse26 Right - sounds good. I'm still having issues trying to install the newer version on my server. I tried on two very different servers - If you'd like to see them yourself, go to https://eddiejibson.com/PHP-Login/install/ and http://eddiej.pw/PHP-Login/install/ . Any ideas? I've tried manually installing them too, but as I said before, they don't create the users - just load in an infinite loop. A much older version worked fine for me.

Thanks.

**Comment by therecluse26** [comment]
Huh, are there any errors being logged in your php_errors.log file?

**Comment by eddiethejibson** [comment]
@therecluse26 No, that's the first thing I checked.

All server's PHP and SQL versions are up to date.

**Comment by therecluse26** [comment]
Try adding this to the top of the php code of the index.php page within the
install folder

error_reporting(E_ALL);
ini_set('display_errors', 1);

**Comment by therecluse26** [comment]
This will be helpful for me in trying to try to iron out some of these compatibility issues and issues with the installer. Are you on a linux server?

**Comment by eddiethejibson** [comment]
@therecluse26 Of course! Both CentOS. One running cPanel installation (which is what a lot of people will be using to install on, I assume) and the other Sentora as I don't need to manage loads of clients on that one.

Thanks again.

**Comment by therecluse26** [comment]
Okay, yeah I haven't tested this on cPanel, but I'll try it out. I'm hoping
that it doesn't limit some of the necessary functionality too much. For
example, this script uses shell_exec features for certain things, which may
be disabled with some hosting providers, it's hard to say. The requirements
will be outlined in my upcoming readme docs

**Comment by eddiethejibson** [comment]
Odd. I'm hosting both panels myself and haven't put any restrictions on that...

**Comment by therecluse26** [comment]
Yeah, I dunno for sure.. were you able to get errors to output?

**Comment by eddiethejibson** [comment]
@therecluse26 Could do, briefly looked over earlier but nothing stood out. I can look further tomorrow. Just seems a bit coincidental that two different panels, on two different servers, on two different versions of CentOS have the same error...

What were/are you using to test it on?

**Comment by therecluse26** [comment]
I'm developing primarily on mac, but I've tested it extensively on Gentoo and Ubuntu with no issues, and am working on Windows compatibility.

**Comment by therecluse26** [comment]
I'll push my changes tonight and you can pull the newest updates to see if any of that helps also.

**Comment by eddiethejibson** [comment]
@therecluse26 Great, thank-you. I'll keep you updated. I think I have a few ideas for names by the way, but haven't finalized them yet. I'll be happy to buy the .com or something that redirects to GitHub pages or whatever you plan to use.

**Comment by therecluse26** [comment]
Sweet! Bounce some ideas off of me and we'll see what we can do. If you
want to discuss this elsewhere, I made a gitter channel for collaborators
to chat on here https://gitter.im/PHP-Login/Lobby

**Comment by therecluse26** [comment]
Here, rather:
https://gitter.im/PHP-Login/Lobby?utm_source=share-link&utm_medium=link&utm_campaign=share-link
