### ISSUE TITLE
Ability to secure folders?

### ISSUE THREAD

**Issue by quavoce** [fethica/PHP-Login#67]
Is there a good way to secure folders within the web root directory please?

For example, RPi Web Cam (for which I'm using PHP-Login with) has a /webroot/media folder that is exposed to browsing and direct media downloading when given the right URL.

I've locked the folder down by using a simple php redirect within index.php using the one liner below, but I'm not sure how to protect media from direct downloads.

`<?php header("location:../"); ?>`

Is this something you've considered for the new version or is there a way for me to lock it down before that's released?

Thanks.

**Comment by therecluse26** [comment]
I would just set the proper permission value using chmod... I'm not sure
what your specific use case is, but I would say that something like 640 or
600 would be safe, depending on your configuration and needs.
