### ISSUE TITLE
PHPMailer @ 9e4b8fb	Update PHPMailer submodule to v5.2.19

### ISSUE THREAD

**Issue by daveclifford** [fethica/PHP-Login#70]
PHP-Login/login/scripts/PHPMailer @ 9e4b8fb is a folder and is not automatically downloaded when downloading the fethica/PHP-Login package from GitHub.

I had to download the PHPMailer from GitHub - PHPMailer/PHPMailer into the folder for the PHPMailer to send e-mails to verify user signup. 

I received an error that the package was missing until I d/led to PHPMailer package to the /login/scripts/PHPMailer.

Please consider a note in the .MD file to that effect.

see "PHPMailer @ 9e4b8fb	Update PHPMailer submodule to v5.2.19"

**Comment by daveclifford** [comment]
did not see this "git clone --recursive https://github.com/fethica/PHP-Login.git" used zip d/l instead - which doesn't recurse.

**Comment by therecluse26** [comment]
Alternatively, you can do run submodule init and update
