### ISSUE TITLE
Error in login (production website)

### ISSUE THREAD

**Issue by phprocks** [fethica/PHP-Login#82]
Hello,

I published your script on my website and when trying to login it is only "processing".

In my development environment it worked normally. The only difference is that in the production environment PHP is 5.2. Does it work in this version?

![erro-login](https://cloud.githubusercontent.com/assets/1650192/24876068/a5a1ce9c-1e00-11e7-9f78-705405d78950.jpg)

**Comment by therecluse26** [comment]
No, unfortunately it utilizes functions that are only available in versions
5.5+

**Comment by phprocks** [comment]
Okay, thanks for answering fast.
