### ISSUE TITLE
Get the logged-on current user

### ISSUE THREAD

**Issue by danionescu2007** [fethica/PHP-Login#90]
Is it possible to call a variable which would return the current user which is validated via <?php require "login/loginheader.php"; ?> in a page which is authenticated with this method?
Thank you,
Dan

**Comment by jontek2** [comment]
Just use the following to get username from SESSION:
`echo '<pre>' . print_r($_SESSION, TRUE) . '</pre>';`

**Comment by danionescu2007** [comment]
Thank you so much!
