### ISSUE TITLE
Creating user Manually in DB

### ISSUE THREAD

**Issue by jamiec1770** [fethica/PHP-Login#97]
Hi guys, imtrying to create a user in the 'members' tables manually via phpmyadmin. 

I can create the user, with n problem however the password i enter is not encrypted with a password hash (generated via the createuser.php) and is displayed as what i entered into the password column (e.g 1234).

Anyone know how to create a user manually via phpmyadmin that also hashes the password?

**Comment by jamiec1770** [comment]
never mind.... i figured it out...im an idiot

used the 'PASSWORD' function in for the password column......duh

**Comment by brianjcollins** [comment]
The password in the database is stored as a VARCHAR, so the hashing occurs in PHP, not in SQL.  To simulate that process, you can from a command line run the following and paste the result into your password column.

```
php -r 'echo password_hash(mypassword, PASSWORD_DEFAULT);'
$2y$10$pvE2bq.ITxpeS8VrAV7Jg.zKCnUjGRmdqptsCpy.ulN9OD38BJwPu
```

**Comment by jamiec1770** [comment]
Nice one Brian.
